// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: CarTouchScreenMiniDisplay

#include "../ui.h"

void ui_Inclinometer_screen_init(void)
{
    ui_Inclinometer = lv_obj_create(NULL);

    ui_RollA = lv_arc_create(ui_Inclinometer);
    lv_obj_set_width(ui_RollA, 217);
    lv_obj_set_height(ui_RollA, 214);
    lv_obj_set_x(ui_RollA, 1);
    lv_obj_set_y(ui_RollA, -1);
    lv_obj_set_align(ui_RollA, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RollA, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_RollA, 50);
    lv_arc_set_bg_angles(ui_RollA, 135, 225);
    lv_obj_set_style_arc_color(ui_RollA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RollA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_RollA, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_RollA, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_RollA, lv_color_hex(0xFF8900), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RollA, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_RollA, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_RollA, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_RollA, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_RollB = lv_arc_create(ui_Inclinometer);
    lv_obj_set_width(ui_RollB, 217);
    lv_obj_set_height(ui_RollB, 214);
    lv_obj_set_x(ui_RollB, 1);
    lv_obj_set_y(ui_RollB, -1);
    lv_obj_set_align(ui_RollB, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RollB, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_RollB, 50);
    lv_arc_set_bg_angles(ui_RollB, 315, 45);
    lv_arc_set_mode(ui_RollB, LV_ARC_MODE_REVERSE);
    lv_obj_set_style_arc_color(ui_RollB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RollB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_RollB, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_RollB, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_RollB, lv_color_hex(0xFF8900), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RollB, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_RollB, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_RollB, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_RollB, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LateralScale = lv_img_create(ui_Inclinometer);
    lv_img_set_src(ui_LateralScale, &ui_img_scale_png);
    lv_obj_set_width(ui_LateralScale, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LateralScale, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LateralScale, 2);
    lv_obj_set_y(ui_LateralScale, -2);
    lv_obj_set_align(ui_LateralScale, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LateralScale, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LateralScale, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_LateralScale, 357);

    ui_Pitch = lv_slider_create(ui_Inclinometer);
    lv_slider_set_range(ui_Pitch, 10, 100);
    lv_slider_set_value(ui_Pitch, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Pitch) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Pitch, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Pitch, 70);
    lv_obj_set_height(ui_Pitch, 105);
    lv_obj_set_x(ui_Pitch, 1);
    lv_obj_set_y(ui_Pitch, -9);
    lv_obj_set_align(ui_Pitch, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Pitch, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Pitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pitch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Pitch, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Pitch, lv_color_hex(0xFF8900), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Pitch, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Pitch, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Pitch, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Pitch, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Pitch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Pitch, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Pitch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_Pitch, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Pitch, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_HeadingDegrees = lv_label_create(ui_Inclinometer);
    lv_obj_set_width(ui_HeadingDegrees, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeadingDegrees, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeadingDegrees, 31);
    lv_obj_set_y(ui_HeadingDegrees, -191);
    lv_obj_set_align(ui_HeadingDegrees, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_HeadingDegrees, "360");
    lv_obj_set_style_text_font(ui_HeadingDegrees, &ui_font_HeadingDegree, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompassDir = lv_label_create(ui_Inclinometer);
    lv_obj_set_width(ui_CompassDir, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CompassDir, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CompassDir, -33);
    lv_obj_set_y(ui_CompassDir, -86);
    lv_obj_set_align(ui_CompassDir, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CompassDir, "SW");
    lv_obj_set_style_text_font(ui_CompassDir, &ui_font_HeadingDegree, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PitchText = lv_label_create(ui_Inclinometer);
    lv_obj_set_width(ui_PitchText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PitchText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PitchText, -35);
    lv_obj_set_y(ui_PitchText, 86);
    lv_obj_set_align(ui_PitchText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PitchText, "-45");
    lv_obj_set_style_text_font(ui_PitchText, &ui_font_HeadingDegree, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollText = lv_label_create(ui_Inclinometer);
    lv_obj_set_width(ui_RollText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RollText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RollText, 28);
    lv_obj_set_y(ui_RollText, 87);
    lv_obj_set_align(ui_RollText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RollText, "-45");
    lv_obj_set_style_text_font(ui_RollText, &ui_font_HeadingDegree, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PitchName = lv_label_create(ui_Inclinometer);
    lv_obj_set_width(ui_PitchName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PitchName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PitchName, -19);
    lv_obj_set_y(ui_PitchName, 60);
    lv_obj_set_align(ui_PitchName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PitchName, "Pitch");
    lv_obj_set_style_text_font(ui_PitchName, &ui_font_SmallerEmblemaOne, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollName = lv_label_create(ui_Inclinometer);
    lv_obj_set_width(ui_RollName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RollName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RollName, 22);
    lv_obj_set_y(ui_RollName, 60);
    lv_obj_set_align(ui_RollName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RollName, "Roll");
    lv_obj_set_style_text_font(ui_RollName, &ui_font_SmallerEmblemaOne, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Inclinometer, ui_event_Inclinometer, LV_EVENT_ALL, NULL);
    uic_RollA = ui_RollA;
    uic_RollB = ui_RollB;
    uic_Pitch = ui_Pitch;
    uic_HeadingDegrees = ui_HeadingDegrees;
    uic_CompassDir = ui_CompassDir;
    uic_PitchText = ui_PitchText;
    uic_RollText = ui_RollText;

}
