// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: CarTouchScreenMiniDisplay

#include "../ui.h"

void ui_Inclinometer_screen_init(void)
{
    ui_Inclinometer = lv_obj_create(NULL);

    ui_InclinationA = lv_arc_create(ui_Inclinometer);
    lv_obj_set_width(ui_InclinationA, 217);
    lv_obj_set_height(ui_InclinationA, 214);
    lv_obj_set_x(ui_InclinationA, 1);
    lv_obj_set_y(ui_InclinationA, -1);
    lv_obj_set_align(ui_InclinationA, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_InclinationA, 50);
    lv_arc_set_bg_angles(ui_InclinationA, 135, 225);
    lv_obj_set_style_arc_color(ui_InclinationA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_InclinationA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_InclinationA, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_InclinationA, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_InclinationA, lv_color_hex(0x8F5818), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_InclinationA, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_InclinationA, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_InclinationA, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_InclinationA, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LateralScale = lv_img_create(ui_Inclinometer);
    lv_img_set_src(ui_LateralScale, &ui_img_scale_drawio_png);
    lv_obj_set_width(ui_LateralScale, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LateralScale, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LateralScale, 2);
    lv_obj_set_y(ui_LateralScale, 0);
    lv_obj_set_align(ui_LateralScale, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LateralScale, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LateralScale, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_LateralScale, 357);

    lv_obj_add_event_cb(ui_Inclinometer, ui_event_Inclinometer, LV_EVENT_ALL, NULL);

}
