// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: CarTouchScreenMiniDisplay

#ifndef _CARTOUCHSCREENMINIDISPLAY_UI_H
#define _CARTOUCHSCREENMINIDISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Inclinometer
void ui_Inclinometer_screen_init(void);
void ui_event_Inclinometer(lv_event_t * e);
extern lv_obj_t * ui_Inclinometer;
extern lv_obj_t * ui_InclinationA;
extern lv_obj_t * ui_LateralScale;
// CUSTOM VARIABLES

// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
void ui_event_Screen7(lv_event_t * e);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Switch2;
// CUSTOM VARIABLES

// SCREEN: ui_Temperature
void ui_Temperature_screen_init(void);
void ui_event_Temperature(lv_event_t * e);
extern lv_obj_t * ui_Temperature;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_scale_drawio_png);    // assets/Scale.drawio.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
