// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: CarTouchScreenMiniDisplay

#ifndef _CARTOUCHSCREENMINIDISPLAY_UI_H
#define _CARTOUCHSCREENMINIDISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Inclinometer
void ui_Inclinometer_screen_init(void);
void ui_event_Inclinometer(lv_event_t * e);
extern lv_obj_t * ui_Inclinometer;
extern lv_obj_t * ui_RollA;
extern lv_obj_t * ui_RollB;
extern lv_obj_t * ui_LateralScale;
extern lv_obj_t * ui_Pitch;
extern lv_obj_t * ui_HeadingDegrees;
extern lv_obj_t * ui_CompassDir;
extern lv_obj_t * ui_PitchText;
extern lv_obj_t * ui_RollText;
extern lv_obj_t * ui_PitchName;
extern lv_obj_t * ui_RollName;
extern lv_obj_t * ui_RollBar;
// CUSTOM VARIABLES
extern lv_obj_t * uic_RollA;
extern lv_obj_t * uic_RollB;
extern lv_obj_t * uic_Pitch;
extern lv_obj_t * uic_HeadingDegrees;
extern lv_obj_t * uic_CompassDir;
extern lv_obj_t * uic_PitchText;
extern lv_obj_t * uic_RollText;
extern lv_obj_t * uic_RollBar;

// SCREEN: ui_Temperature
void ui_Temperature_screen_init(void);
void ui_event_Temperature(lv_event_t * e);
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_TempLabel;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_scale_png);    // assets/Scale.png
LV_IMG_DECLARE(ui_img_pitchbar_png);    // assets/PitchBar.png

// FONTS
LV_FONT_DECLARE(ui_font_Nabla_Big);
LV_FONT_DECLARE(ui_font_HeadingDegree);
LV_FONT_DECLARE(ui_font_SmallerEmblemaOne);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
