// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: CarTouchScreenMiniDisplay

#include "../ui.h"

void ui_Slider_screen_init(void)
{
    ui_Slider = lv_obj_create(NULL);

    ui_Arc2 = lv_arc_create(ui_Slider);
    lv_obj_set_width(ui_Arc2, 227);
    lv_obj_set_height(ui_Arc2, 218);
    lv_obj_set_x(ui_Arc2, 5);
    lv_obj_set_y(ui_Arc2, -1);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc2, 50);

    lv_obj_add_event_cb(ui_Slider, ui_event_Slider, LV_EVENT_ALL, NULL);

}
