// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: CarTouchScreenMiniDisplay

#include "../ui.h"

void ui_Temperature_screen_init(void)
{
    ui_Temperature = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Temperature, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Temperature, ui_event_Temperature, LV_EVENT_ALL, NULL);

}
